-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-04-28 01:29:22 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE company (
    company_name     VARCHAR2(100) NOT NULL,
    country_c_code   VARCHAR2(30) NOT NULL
);

ALTER TABLE company ADD CONSTRAINT company_pk PRIMARY KEY ( company_name,
                                                            country_c_code );

CREATE TABLE company_film (
    company_company_name   VARCHAR2(100) NOT NULL,
    company_c_code         VARCHAR2(30) NOT NULL,
    film_film_name         VARCHAR2(100) NOT NULL,
    film_director          VARCHAR2(40) NOT NULL
);

ALTER TABLE company_film
    ADD CONSTRAINT company_film_pk PRIMARY KEY ( company_company_name,
                                                 company_c_code,
                                                 film_film_name,
                                                 film_director );

CREATE TABLE country (
    c_code VARCHAR2(30) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( c_code );

CREATE TABLE film (
    film_name      VARCHAR2(100) NOT NULL,
    director       VARCHAR2(40) NOT NULL,
    release_date   DATE,
    budget         NUMBER(12, 1),
    income         NUMBER(13, 1)
);

ALTER TABLE film ADD CONSTRAINT film_pk PRIMARY KEY ( film_name,
                                                      director );

CREATE TABLE film_genre (
    genre_genre_name   VARCHAR2(20) NOT NULL,
    film_film_name     VARCHAR2(100) NOT NULL,
    film_director      VARCHAR2(40) NOT NULL
);

ALTER TABLE film_genre
    ADD CONSTRAINT film_genre_pk PRIMARY KEY ( genre_genre_name,
                                               film_film_name,
                                               film_director );

CREATE TABLE genre (
    genre_name VARCHAR2(20) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( genre_name );

ALTER TABLE company
    ADD CONSTRAINT company_country_fk FOREIGN KEY ( country_c_code )
        REFERENCES country ( c_code );

ALTER TABLE company_film
    ADD CONSTRAINT company_film_company_fk FOREIGN KEY ( company_company_name,
                                                         company_c_code )
        REFERENCES company ( company_name,
                             country_c_code );

ALTER TABLE company_film
    ADD CONSTRAINT company_film_film_fk FOREIGN KEY ( film_film_name,
                                                      film_director )
        REFERENCES film ( film_name,
                          director );

ALTER TABLE film_genre
    ADD CONSTRAINT film_genre_film_fk FOREIGN KEY ( film_film_name,
                                                    film_director )
        REFERENCES film ( film_name,
                          director );

ALTER TABLE film_genre
    ADD CONSTRAINT film_genre_genre_fk FOREIGN KEY ( genre_genre_name )
        REFERENCES genre ( genre_name );

